### ISSUE TITLE
Looking forward that you can open sourse your train code

### ISSUE THREAD

**Issue by mnoiy** [ryangchn/QG-ConvLSTM#1]
hello,Do you mind to share your train code ? 
I think it would be very helpful for my learning~

**Comment by AlexSun0110** [comment]
您好，我是最近正在做压缩视频质量增强。看到您似乎也在做这个研究，不知道可否加下联系方式进行些交流呢。十分感谢！我的邮箱：alexsun0110@qq.com

**Comment by AlexSun0110** [comment]
> 您好，您介意分享您的火车代码吗？
> 我觉得这对我的学习很有帮助〜

您好，我是最近正在做压缩视频质量增强。看到您似乎也在做这个研究，不知道可否加下联系方式进行些交流呢。十分感谢！我的邮箱：alexsun0110@qq.com

**Comment by RenYang-home** [comment]
We will not release the training codes, but would like to help if you have any question in training. My contact: ren.yang@vision.ee.ethz.ch

**Comment by ryangBUAA** [comment]
We will not release the training codes, but would like to help if you have any question in training. My contact: ren.yang@vision.ee.ethz.ch
